// audio_mix_test.dart — the shipping mix must be audible ON A PHONE.
//
// The alpha.4 set failed this badly: land.ogg had 100 % of its energy below
// 300 Hz, player_hit 99.4 %, enemy_death 99.8 %, jump 96.6 %, and the music
// beds 88-91 %. A phone loudspeaker projects almost nothing under ~500 Hz, so
// those cues were effectively silent on the device the game ships to while a
// handful of bright sounds were 20 dB louder. This test pins the fix:
//
//   * every one-shot puts a real share of its energy in the band a phone can
//     actually reproduce (>= 500 Hz)
//   * the set is level-matched, so nothing blasts and nothing vanishes
//   * every level references a music bed, and more than one bed is used
//
// It reads the OGG headers + decoded PCM through a tiny built-in Vorbis
// energy probe? No — decoding Vorbis in pure Dart is out of scope, so the
// contract is enforced on the METADATA the build script emits
// (tool/audio_mix.json, regenerated by tool/build_audio_v3.py) plus the
// level/AudioService wiring, which is what regressions actually break.
import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

import 'package:pyregrove/audio/audio_service.dart';
import 'package:pyregrove/game/level/level_data.dart';

void main() {
  group('mix report (tool/audio_mix.json)', () {
    late Map<String, dynamic> report;

    setUpAll(() {
      final f = File('tool/audio_mix.json');
      expect(f.existsSync(), isTrue,
          reason: 'run tool/build_audio_v3.py + tool/build_music_v3.py');
      report = jsonDecode(f.readAsStringSync()) as Map<String, dynamic>;
    });

    test('every SFX id has a measured entry', () {
      final sfx = report['sfx'] as Map<String, dynamic>;
      for (final id in AudioService.sfxPaths.keys) {
        expect(sfx.containsKey(id), isTrue, reason: 'no mix entry for $id');
      }
    });

    test('one-shots carry their energy in the phone-speaker band', () {
      final sfx = report['sfx'] as Map<String, dynamic>;
      final offenders = <String>[];
      for (final e in sfx.entries) {
        final above500 = (e.value['above500'] as num).toDouble();
        if (above500 < 0.35) offenders.add('${e.key} ${(above500 * 100).round()}%');
      }
      expect(offenders, isEmpty,
          reason: 'sounds a phone speaker cannot reproduce: $offenders');
    });

    test('the set is level-matched (no 20 dB surprises)', () {
      final sfx = report['sfx'] as Map<String, dynamic>;
      // Foreground one-shots share one target; beds/footsteps/UI are
      // deliberately quieter and declared as such by the build script.
      final fg = [
        for (final e in sfx.entries)
          if (e.value['group'] == 'foreground')
            (e.value['phoneRms'] as num).toDouble()
      ];
      expect(fg.length, greaterThan(10));
      final lo = fg.reduce((a, b) => a < b ? a : b);
      final hi = fg.reduce((a, b) => a > b ? a : b);
      expect(hi - lo, lessThan(4.0),
          reason: 'foreground sfx spread ${(hi - lo).toStringAsFixed(1)} dB');
    });

    test('music beds are mixed under the sfx', () {
      final music = report['music'] as Map<String, dynamic>;
      expect(music, isNotEmpty);
      for (final e in music.entries) {
        final rms = (e.value['phoneRms'] as num).toDouble();
        expect(rms, lessThan(-24.0), reason: '${e.key} bed is too loud');
        expect(rms, greaterThan(-29.0), reason: '${e.key} bed is too quiet');
      }
    });
  });

  test('levels do not all share one music bed', () {
    final used = <String>{};
    for (final f in Directory('assets/levels').listSync().whereType<File>()) {
      if (!f.path.endsWith('.txt')) continue;
      final level = LevelData.parse(f.readAsStringSync());
      expect(AudioService.musicPaths.containsKey(level.music), isTrue,
          reason: '${f.path}: unknown music "${level.music}"');
      used.add(level.music);
    }
    expect(used.length, greaterThanOrEqualTo(3),
        reason: 'twelve levels sharing one loop is what "the audio is '
            'repetitive" means; found $used');
  });

  test('boss arenas use the boss bed', () {
    for (final id in ['w1_boss', 'w2_boss']) {
      final level =
          LevelData.parse(File('assets/levels/$id.txt').readAsStringSync());
      expect(level.music, 'boss_combat');
    }
  });

  test('pitch variance: varied ids wobble in [0.94, 1.06], others stay 1.0', () {
    // Bounds at the extremes of the unit draw.
    expect(AudioService.sfxRateFor('coin', 0.0), closeTo(0.94, 1e-9));
    expect(AudioService.sfxRateFor('coin', 0.999999), lessThan(1.06));
    // Stable ids never wobble regardless of the draw.
    for (final id in ['medal', 'secret', 'victory', 'ui_tap', 'jump']) {
      expect(AudioService.sfxRateFor(id, 0.5), 1.0, reason: id);
    }
    // Every varied id must actually exist in sfxPaths (no typos).
    for (final id in AudioService.variedSfx) {
      expect(AudioService.sfxPaths.containsKey(id), isTrue, reason: id);
    }
  });
}
