// PlayerComponent: draws PlayerCore state. NO gameplay logic here — the core
// (via the session) owns movement/combat; this picks animation strips, flips
// by facing, and blinks during i-frames.
import 'dart:math' as math;
import 'dart:ui' as ui;

import 'package:flame/components.dart';
import 'package:flame/sprite.dart';

import '../ember_game.dart';
import '../player/player_core.dart';
import '../tuning.dart';
import '../../meta/catalog.dart';

class PlayerComponent extends PositionComponent
    with HasGameReference<EmberGame> {
  PlayerComponent() : super(priority: 3);

  late final Map<PlayerState, SpriteAnimation> _anims;
  late final List<SpriteAnimation> _attacks; // by comboIndex
  // AKP-4a: the equipped weapon is a separate overlay sheet with identical
  // frame geometry, driven by a second ticker in lockstep with the body's.
  // Maps are empty when the weapon sheets are missing (catalog/art drift):
  // the knight simply renders bare-handed rather than crashing.
  final Map<PlayerState, SpriteAnimation> _weaponAnims = {};
  final List<SpriteAnimation> _weaponAttacks = [];
  SpriteAnimation? _current;
  SpriteAnimationTicker? _ticker;
  SpriteAnimationTicker? _weaponTicker;
  double _blinkClock = 0;

  // AKP-3a: landing squash-and-stretch. Set from ember_game on the landed
  // event; decays here. Render-only — the body/hitbox never changes.
  static const double _squashTime = 0.08;
  double _squash = 0;

  void triggerSquash() => _squash = _squashTime;

  // Takeoff stretch — the classic pairing for the landing squash (narrower
  // and taller for ~100ms as the jump starts, anchored at the feet). Adds
  // anticipation weight to every jump; render-only like the squash.
  static const double _stretchTime = 0.10;
  double _stretch = 0;

  void triggerStretch() => _stretch = _stretchTime;

  /// Test hooks: squash/stretch are render-only state with a fixed decay.
  bool get squashActive => _squash > 0;
  bool get stretchActive => _stretch > 0;
  void decaySquash(double dt) {
    _squash = math.max(0, _squash - dt);
    _stretch = math.max(0, _stretch - dt);
  }

  // AKP-3b: swing-arc overlay, tinted per weapon special. One paint reused
  // across frames; the arc path is rebuilt only while attacking.
  static final _arcPaint = ui.Paint()
    ..style = ui.PaintingStyle.stroke
    ..strokeCap = ui.StrokeCap.round;
  static const _specialTints = {
    WeaponSpecial.none: ui.Color(0xE6F4EFE6),
    WeaponSpecial.wallBreaker: ui.Color(0xE6D8CDBd),
    WeaponSpecial.burn: ui.Color(0xE6F2A24B),
    WeaponSpecial.bonusHeart: ui.Color(0xE6E8848D),
    WeaponSpecial.lunge: ui.Color(0xE6A9D1F7),
    WeaponSpecial.tripleJump: ui.Color(0xE6BFE8A9),
  };

  // Scratch vectors reused every frame (Sprite.render copies them into its
  // own temps; it never keeps the reference) — no per-frame allocations.
  static final _drawPos = Vector2.zero();
  static final _drawSize = Vector2.zero();

  /// Sheet path for the equipped skin. 'red' (starter) = the bladeless body
  /// sheets in player/body/; other catalog skins are recolors of those
  /// generated by tool/build_skins.py (AKP-4a split the baked-in sword out —
  /// tool/build_weapon_sprites.py). Falls back to the original bladed base
  /// sheet if body/skin files are missing, so art drift can never crash a run.
  Future<ui.Image> _sheet(String name) async {
    final skin = game.session.loadout.skinId;
    if (skin != 'red') {
      try {
        return await game.images.load('player/skins/$skin/$name.png');
      } catch (_) {/* fall through to base */}
    }
    try {
      return await game.images.load('player/body/$name.png');
    } catch (_) {
      return game.images.load('player/$name.png');
    }
  }

  Future<SpriteAnimation> _load(
      String name, int frames, Vector2 size, double stepTime,
      {bool loop = true}) async {
    return SpriteAnimation.fromFrameData(
      await _sheet(name),
      SpriteAnimationData.sequenced(
          amount: frames, stepTime: stepTime, textureSize: size, loop: loop),
    );
  }

  /// AKP-4a: equipped-weapon overlay animation, frame-for-frame parallel to
  /// the body animation. Null when the sheet is missing.
  Future<SpriteAnimation?> _loadWeapon(
      String name, int frames, Vector2 size, double stepTime,
      {bool loop = true}) async {
    final weaponId = game.session.loadout.weapon.id;
    try {
      final img = await game.images.load('player/weapons/$weaponId/$name.png');
      return SpriteAnimation.fromFrameData(
        img,
        SpriteAnimationData.sequenced(
            amount: frames, stepTime: stepTime, textureSize: size, loop: loop),
      );
    } catch (_) {
      return null;
    }
  }

  @override
  Future<void> onLoad() async {
    final s22 = Vector2(22, 24);
    final s40 = Vector2(40, 30);
    _anims = {
      PlayerState.idle: await _load('idle', 5, s22, 0.12),
      PlayerState.run: await _load('run', 6, s22, 0.09),
      PlayerState.jump: await _load('jump', 4, s22, 0.08, loop: false),
      PlayerState.fall: await _load('fall', 4, s22, 0.08, loop: false),
      PlayerState.roll:
          await _load('roll', 11, s22, kRollDuration / 11, loop: false),
      PlayerState.hurt: await _load('hit', 6, s22, 0.05, loop: false),
      PlayerState.dead: await _load('hit', 6, s22, 0.05, loop: false),
    };
    _attacks = [
      await _load('attack1', 10, s40, kAttackDuration / 10, loop: false),
      await _load('attack2', 12, s40, kAttackDuration / 12, loop: false),
      await _load('attack3', 8, s40, kAttackDuration / 8, loop: false),
    ];
    // AKP-4a: weapon overlays mirror the body sets exactly.
    for (final e in {
      PlayerState.idle: ('idle', 5, s22, 0.12, true),
      PlayerState.run: ('run', 6, s22, 0.09, true),
      PlayerState.jump: ('jump', 4, s22, 0.08, false),
      PlayerState.fall: ('fall', 4, s22, 0.08, false),
      PlayerState.roll: ('roll', 11, s22, kRollDuration / 11, false),
      PlayerState.hurt: ('hit', 6, s22, 0.05, false),
      PlayerState.dead: ('hit', 6, s22, 0.05, false),
    }.entries) {
      final (name, frames, size, step, loop) = e.value;
      final anim = await _loadWeapon(name, frames, size, step, loop: loop);
      if (anim != null) _weaponAnims[e.key] = anim;
    }
    for (final (name, frames, step) in [
      ('attack1', 10, kAttackDuration / 10),
      ('attack2', 12, kAttackDuration / 12),
      ('attack3', 8, kAttackDuration / 8),
    ]) {
      final anim = await _loadWeapon(name, frames, s40, step, loop: false);
      if (anim == null) {
        _weaponAttacks.clear(); // all-or-nothing: keep indices aligned
        break;
      }
      _weaponAttacks.add(anim);
    }
    _setAnim(_anims[PlayerState.idle]!, _weaponAnims[PlayerState.idle]);
  }

  void _setAnim(SpriteAnimation anim, SpriteAnimation? weaponAnim) {
    if (identical(anim, _current)) return;
    _current = anim;
    _ticker = anim.createTicker();
    _weaponTicker = weaponAnim?.createTicker();
  }

  @override
  void update(double dt) {
    final core = game.session.player;
    _blinkClock += dt;
    decaySquash(dt);
    if (core.state == PlayerState.attack) {
      final i = core.comboIndex.clamp(0, _attacks.length - 1);
      _setAnim(_attacks[i],
          i < _weaponAttacks.length ? _weaponAttacks[i] : null);
    } else {
      _setAnim(_anims[core.state]!, _weaponAnims[core.state]);
    }
    _ticker?.update(dt);
    _weaponTicker?.update(dt);
  }

  @override
  void render(ui.Canvas canvas) {
    final core = game.session.player;
    final ticker = _ticker;
    if (ticker == null) return;
    // Blink during i-frames (skip every other 0.08s window).
    if (core.iFrames > 0 &&
        !core.isDead &&
        (_blinkClock / 0.08).floor().isEven) {
      return;
    }
    final sprite = ticker.getSprite();
    final w = sprite.srcSize.x, h = sprite.srcSize.y;
    // Anchor the frame bottom-center on the body's bottom-center.
    final b = core.body;
    canvas.save();
    if (core.facing < 0) {
      canvas.translate(b.centerX * 2, 0);
      canvas.scale(-1, 1);
    }
    // AKP-3a: squash on landing — wider and shorter, anchored at the feet,
    // easing back to 1:1 over ~80ms. Pure render transform.
    if (_squash > 0) {
      final k = _squash / _squashTime; // 1 -> 0
      final sx = 1 + 0.15 * k, sy = 1 - 0.15 * k;
      canvas.translate(b.centerX, b.bottom);
      canvas.scale(sx, sy);
      canvas.translate(-b.centerX, -b.bottom);
    } else if (_stretch > 0) {
      // Takeoff: narrower and taller. Squash wins if both are live (landing
      // is always the more recent, more grounding beat).
      final k = _stretch / _stretchTime; // 1 -> 0
      final sx = 1 - 0.10 * k, sy = 1 + 0.10 * k;
      canvas.translate(b.centerX, b.bottom);
      canvas.scale(sx, sy);
      canvas.translate(-b.centerX, -b.bottom);
    }
    _drawPos.setValues(b.centerX - w / 2, b.bottom - h);
    _drawSize.setValues(w, h);
    sprite.render(canvas, position: _drawPos, size: _drawSize);
    // AKP-4a: equipped-weapon overlay, same transform and frame geometry —
    // it flips, squashes and blinks exactly with the body.
    final weaponSprite = _weaponTicker?.getSprite();
    if (weaponSprite != null) {
      weaponSprite.render(canvas, position: _drawPos, size: _drawSize);
    }
    // AKP-3b: swing arc — a white crescent sweeping with the attack frame,
    // in front of the player, tinted per weapon special. This is the single
    // biggest "reads like AK" win in combat (docs/ak-parity-plan.md §3).
    if (core.state == PlayerState.attack) {
      final progress =
          (ticker.clock / ticker.totalDuration()).clamp(0.0, 1.0);
      // The arc lives in the swing's middle 60%: wind-up and recovery bare.
      if (progress > 0.15 && progress < 0.75) {
        final swing = (progress - 0.15) / 0.6; // 0..1 across the arc
        final radius = 14.0 + game.session.loadout.weapon.range * 0.5;
        // Alternate sweep direction by combo step so the phrase reads
        // down-slash / up-slash / big down-slash.
        final up = core.comboIndex == 1;
        final start = up ? 0.9 - swing * 1.8 : -0.9 + swing * 1.8;
        _arcPaint
          ..color = _specialTints[game.session.loadout.weapon.special] ??
              const ui.Color(0xE6F4EFE6)
          ..strokeWidth = core.comboIndex == 2 ? 3.0 : 2.0;
        canvas.drawArc(
          ui.Rect.fromCircle(
              center: ui.Offset(b.centerX + radius * 0.35,
                  b.centerY - 2),
              radius: radius),
          start - 0.35,
          0.7,
          false,
          _arcPaint,
        );
      }
    }
    canvas.restore();
  }
}
